<?php
/**
 * Project Odysseus — application configuration.
 *
 * This file IS tracked in git. It contains no credentials: everything
 * secret is read from .env at the repo root (see .env.example).
 *
 * Structural settings — paths, ingest limits, storage guardrails, Shopify
 * scopes — belong here so they are version-controlled and reviewable. The
 * server admin never edits this file; they only fill in .env.
 */

declare(strict_types=1);

require_once __DIR__ . '/../app/lib/Env.php';

Env::load(dirname(__DIR__) . '/.env');

$root = dirname(__DIR__);

return [

    // -----------------------------------------------------------------
    // Database — credentials from .env
    // -----------------------------------------------------------------
    'db' => [
        'host'    => Env::get('DB_HOST', 'localhost'),
        'port'    => Env::int('DB_PORT', 3306),
        'user'    => Env::require('DB_USER'),
        'pass'    => Env::get('DB_PASS', ''),

        // Full database names, exactly as the host reports them.
        //
        // 'shard' carries a literal {year} placeholder: raw events get a new
        // database each year because Hostinger caps each at 3 GB, so the code
        // must be able to construct a name for a year it has not seen yet.
        // Once a shard is provisioned, shard_registry.physical_name is the
        // authoritative mapping and this is only used to propose new ones.
        'core'    => Env::require('DB_CORE'),
        'shard'   => Env::require('DB_SHARD'),

        // Per-shard credential overrides, discovered from .env keys shaped
        // DB_SHARD_<YEAR>_USER / _PASS / _NAME.
        //
        // Hostinger issues one credential per database, so each yearly shard
        // normally has its own user. Where a year has no override, the core
        // credentials are used instead — which covers hosts that allow one
        // user across several databases.
        'shard_overrides' => (static function (): array {
            $out = [];
            foreach (Env::allWithPrefix('DB_SHARD_') as $suffix => $value) {
                if (!preg_match('/^(\d{4})_(USER|PASS|NAME)$/', $suffix, $m)) {
                    continue;
                }
                $out[(int) $m[1]][strtolower($m[2])] = $value;
            }
            return $out;
        })(),

        'charset' => 'utf8mb4',
    ],

    // -----------------------------------------------------------------
    // Filesystem
    //
    // These default to directories inside the repository, which is fine for
    // local development but DANGEROUS on a server that deploys by git: a
    // deployment step that runs `git clean` deletes untracked files, and
    // these hold irreplaceable data.
    //
    //   secrets/master.key  - losing it makes every stored Shopify token
    //                         permanently unreadable
    //   storage/spool/      - pixel events not yet imported; unlike orders
    //                         these cannot be backfilled from anywhere
    //
    // On any deployed environment set STORAGE_PATH and SECRETS_PATH in .env
    // to directories OUTSIDE the repository. Runtime data should never share
    // a directory with something a deployment process manages.
    // -----------------------------------------------------------------
    'paths' => (static function () use ($root): array {
        // Default to a sibling of the repository rather than a folder inside
        // it. Inside is the one place these must never live: a git-based
        // deploy that runs `git clean` would delete the encryption key and
        // any pixel events not yet imported.
        //
        // On a Hostinger layout this resolves to
        //   domains/<site>/odysseus-data/...
        // which is outside the repository and above the document root, so the
        // common case needs no configuration at all.
        $default = dirname($root) . '/odysseus-data';

        $storage = rtrim(Env::get('STORAGE_PATH', $default . '/storage'), '/\\');
        $secrets = rtrim(Env::get('SECRETS_PATH', $default . '/secrets'), '/\\');

        return [
            'storage'   => $storage,
            'spool'     => $storage . '/spool',
            'processed' => $storage . '/processed',
            'failed'    => $storage . '/failed',
            'locks'     => $storage . '/locks',
            'logs'      => $storage . '/logs',
            'secrets'   => $secrets,
            'geoip'     => $secrets . '/geoip-city.mmdb',
        ];
    })(),

    'secrets' => (static function () use ($root): array {
        $secrets = rtrim(
            Env::get('SECRETS_PATH', dirname($root) . '/odysseus-data/secrets'),
            '/\\'
        );

        return [
            // Generated by bin/keygen.php or the setup page, never by hand.
            'master_key_file' => $secrets . '/master.key',
            'salt_dir'        => $secrets . '/salts',
        ];
    })(),

    // -----------------------------------------------------------------
    // Single host, path-separated (§4.1). The collector path is short
    // because it is repeated in every beacon on every store.
    // -----------------------------------------------------------------
    'hosts' => [
        'base'           => Env::get('APP_BASE_URL', 'https://retention.digifyce.com'),
        'collect'        => rtrim(Env::get('APP_BASE_URL', 'https://retention.digifyce.com'), '/') . '/c.php',
        'oauth_redirect' => Env::get(
            'SHOPIFY_REDIRECT_URI',
            'https://retention.digifyce.com/oauth/callback.php'
        ),
    ],

    // -----------------------------------------------------------------
    // Ingest limits (§7.1). The write_key in the pixel snippet is PUBLIC
    // and is not a credential — these are the actual protections.
    // -----------------------------------------------------------------
    'ingest' => [
        'max_body_bytes'     => 65536,
        'rate_limit_per_min' => 240,    // per IP per tenant
        'enforce_origin'     => true,   // reject when Origin/Referer host
                                        // does not match the tenant domain
    ],

    // -----------------------------------------------------------------
    // Storage guardrails (§15.3). The shard alarm is a Phase 1
    // deliverable: a full shard means silently dropped events.
    // -----------------------------------------------------------------
    'storage' => [
        'shard_bytes_limit'     => 3221225472,  // 3 GiB
        'shard_warn_ratio'      => 0.80,        // alert at 2.4 GiB
        'processed_retain_days' => 30,          // replay window
    ],

    // -----------------------------------------------------------------
    // Retention after a merchant uninstalls.
    //
    // On the App Store, merchants install, trial for days, and uninstall.
    // Keeping their raw events indefinitely is storage nobody is paying for
    // and personal data held with no relationship to justify it.
    //
    // shop/redact is mandatory and must be honoured within 30 days, so the
    // deletion machinery is required regardless of what these say. These only
    // control the delay, and can change at any time without a migration.
    //
    //   uninstall_purge_days  days after uninstall before raw events are
    //                         deleted. 0 purges immediately.
    //   keep_rollups          rollups are anonymous counts, so retaining them
    //                         is defensible and near-free — and lets a
    //                         returning merchant see their old trend lines.
    //
    // A shop/redact request overrides both and deletes at once.
    // -----------------------------------------------------------------
    'retention' => [
        'uninstall_purge_days' => Env::int('UNINSTALL_PURGE_DAYS', 0),
        'keep_rollups'         => Env::bool('KEEP_ROLLUPS_AFTER_UNINSTALL', true),
        'redact_within_days'   => 30,   // Shopify's requirement; not ours to change
    ],

    'alerts' => [
        'email_to'           => Env::get('ALERT_EMAIL_TO'),
        'email_from'         => Env::get('ALERT_EMAIL_FROM', 'odysseus@digifyce.com'),
        'renotify_after_min' => 360,
    ],

    // -----------------------------------------------------------------
    // Shopify
    // -----------------------------------------------------------------
    'shopify' => [
        // Shopify supports a stable version for 12 months and falls FORWARD
        // silently when yours expires — the app keeps working while no longer
        // being pinned to the behaviour it was written against, which is the
        // worst of both. bin/selftest.php fails when this goes stale.
        //
        // Never a release candidate: Shopify ships breaking changes into
        // those, and the CLI will happily default a new app to one.
        'api_version'   => Env::get('SHOPIFY_API_VERSION', '2026-07'),

        // One app, one credential pair - not one per store. Public
        // distribution means these are ours and live in .env.
        'client_id'     => Env::get('SHOPIFY_CLIENT_ID', ''),
        'client_secret' => Env::get('SHOPIFY_CLIENT_SECRET', ''),

        // Scopes are NOT listed here.
        //
        // They live in exactly two places that must agree: ShopifyOAuth::SCOPES
        // (what the app requests) and [access_scopes] in
        // shopify/shopify.app.toml (what Shopify grants under managed
        // installation). A third copy here would be a third thing to drift,
        // and the drift is silent — the app would ask for one set and receive
        // another with nothing raising an error.
        //
        // ShopifyOAuth::scopesMatchToml() compares the two, and the self-test
        // runs it.
    ],

    // -----------------------------------------------------------------
    // Billing
    //
    // Shopify owns the subscription: it runs the trial, takes the money,
    // retries failed payments and cancels on uninstall. The app's whole
    // job is to create the subscription, send the merchant to Shopify to
    // approve it, and read back what Shopify says the state is. Anything
    // more would be a second source of truth about money.
    //
    // A public app MAY NOT charge outside the Billing API, so there is no
    // alternative to design against.
    // -----------------------------------------------------------------
    'billing' => [
        // OFF by default, deliberately. An app that gates the dashboard
        // before it is listed locks out its own test stores, and the first
        // symptom is a blank screen nobody can explain. Turn it on in .env
        // when the listing is ready.
        'enabled' => Env::bool('BILLING_ENABLED', false),

        // A test subscription bills nothing and is what development and
        // Shopify's own review run on. It MUST be false in production, and
        // Billing::state() reports a test subscription as such so a paying
        // store is never confused with a free one.
        'test' => Env::bool('BILLING_TEST', false),

        'trial_days' => Env::int('BILLING_TRIAL_DAYS', 14),

        // The plans a merchant can choose. One for now: a second tier is a
        // pricing decision, not a code change, and inventing tiers before
        // anyone has paid for the first is how a product ends up defending
        // a feature split nobody asked for.
        //
        // PRICE IS A BUSINESS DECISION AND THIS IS A PLACEHOLDER.
        // Set BILLING_PRICE in .env before listing. Shopify bills app
        // subscriptions in the currency set here, not the store's.
        'plans' => [
            'standard' => [
                'name'     => 'Retention Dashboard',
                'price'    => Env::get('BILLING_PRICE', '19.00'),
                'currency' => Env::get('BILLING_CURRENCY', 'USD'),
                'interval' => 'EVERY_30_DAYS',
                'blurb'    => 'Everything, for one store.',
                'features' => [
                    'Repeat purchase and cohort retention',
                    'Campaign attribution under four models',
                    'Funnel and checkout drop-off',
                    'Product, geography and device reports',
                    'Full history — nothing is sampled or aged out',
                ],
            ],
        ],
    ],

    // Everything is stored UTC. Display timezone is per-tenant.
    'app' => [
        // The app's own public address, e.g. https://retention.digifyce.com
        //
        // Needed wherever a URL has to be absolute and there is no request to
        // read it from: Shopify's billing return URL, and anything sent by
        // cron. Left blank it is derived from the incoming request, which is
        // right in a browser and impossible in a cron job.
        'url'      => rtrim((string) Env::get('APP_URL', ''), '/'),
        'timezone' => 'UTC',
        'debug'    => Env::bool('APP_DEBUG', false),
    ],
];
