<?php
/**
 * Project Odysseus — application configuration.
 *
 * This file IS tracked in git. It contains no credentials: everything
 * secret is read from .env at the repo root (see .env.example).
 *
 * Structural settings — paths, ingest limits, storage guardrails, Shopify
 * scopes — belong here so they are version-controlled and reviewable. The
 * server admin never edits this file; they only fill in .env.
 */

declare(strict_types=1);

require_once __DIR__ . '/../app/lib/Env.php';

Env::load(dirname(__DIR__) . '/.env');

$root = dirname(__DIR__);

return [

    // -----------------------------------------------------------------
    // Database — credentials from .env
    // -----------------------------------------------------------------
    'db' => [
        'host'    => Env::get('DB_HOST', 'localhost'),
        'port'    => Env::int('DB_PORT', 3306),
        'user'    => Env::require('DB_USER'),
        'pass'    => Env::get('DB_PASS', ''),

        // Full database names, exactly as the host reports them.
        //
        // 'shard' carries a literal {year} placeholder: raw events get a new
        // database each year because Hostinger caps each at 3 GB, so the code
        // must be able to construct a name for a year it has not seen yet.
        // Once a shard is provisioned, shard_registry.physical_name is the
        // authoritative mapping and this is only used to propose new ones.
        'core'    => Env::require('DB_CORE'),
        'shard'   => Env::require('DB_SHARD'),

        // Per-shard credential overrides, discovered from .env keys shaped
        // DB_SHARD_<YEAR>_USER / _PASS / _NAME.
        //
        // Hostinger issues one credential per database, so each yearly shard
        // normally has its own user. Where a year has no override, the core
        // credentials are used instead — which covers hosts that allow one
        // user across several databases.
        'shard_overrides' => (static function (): array {
            $out = [];
            foreach (Env::allWithPrefix('DB_SHARD_') as $suffix => $value) {
                if (!preg_match('/^(\d{4})_(USER|PASS|NAME)$/', $suffix, $m)) {
                    continue;
                }
                $out[(int) $m[1]][strtolower($m[2])] = $value;
            }
            return $out;
        })(),

        'charset' => 'utf8mb4',
    ],

    // -----------------------------------------------------------------
    // Filesystem
    //
    // These default to directories inside the repository, which is fine for
    // local development but DANGEROUS on a server that deploys by git: a
    // deployment step that runs `git clean` deletes untracked files, and
    // these hold irreplaceable data.
    //
    //   secrets/master.key  - losing it makes every stored Shopify token
    //                         permanently unreadable
    //   storage/spool/      - pixel events not yet imported; unlike orders
    //                         these cannot be backfilled from anywhere
    //
    // On any deployed environment set STORAGE_PATH and SECRETS_PATH in .env
    // to directories OUTSIDE the repository. Runtime data should never share
    // a directory with something a deployment process manages.
    // -----------------------------------------------------------------
    'paths' => (static function () use ($root): array {
        // Default to a sibling of the repository rather than a folder inside
        // it. Inside is the one place these must never live: a git-based
        // deploy that runs `git clean` would delete the encryption key and
        // any pixel events not yet imported.
        //
        // On a Hostinger layout this resolves to
        //   domains/<site>/odysseus-data/...
        // which is outside the repository and above the document root, so the
        // common case needs no configuration at all.
        $default = dirname($root) . '/odysseus-data';

        $storage = rtrim(Env::get('STORAGE_PATH', $default . '/storage'), '/\\');
        $secrets = rtrim(Env::get('SECRETS_PATH', $default . '/secrets'), '/\\');

        return [
            'storage'   => $storage,
            'spool'     => $storage . '/spool',
            'processed' => $storage . '/processed',
            'failed'    => $storage . '/failed',
            'locks'     => $storage . '/locks',
            'logs'      => $storage . '/logs',
            'secrets'   => $secrets,
            'geolite'   => $secrets . '/GeoLite2-City.mmdb',
        ];
    })(),

    'secrets' => (static function () use ($root): array {
        $secrets = rtrim(
            Env::get('SECRETS_PATH', dirname($root) . '/odysseus-data/secrets'),
            '/\\'
        );

        return [
            // Generated by bin/keygen.php or the setup page, never by hand.
            'master_key_file' => $secrets . '/master.key',
            'salt_dir'        => $secrets . '/salts',
        ];
    })(),

    // -----------------------------------------------------------------
    // Single host, path-separated (§4.1). The collector path is short
    // because it is repeated in every beacon on every store.
    // -----------------------------------------------------------------
    'hosts' => [
        'base'           => Env::get('APP_BASE_URL', 'https://retention.digifyce.com'),
        'collect'        => rtrim(Env::get('APP_BASE_URL', 'https://retention.digifyce.com'), '/') . '/c.php',
        'oauth_redirect' => Env::get(
            'SHOPIFY_REDIRECT_URI',
            'https://retention.digifyce.com/oauth/callback.php'
        ),
    ],

    // -----------------------------------------------------------------
    // Ingest limits (§7.1). The write_key in the pixel snippet is PUBLIC
    // and is not a credential — these are the actual protections.
    // -----------------------------------------------------------------
    'ingest' => [
        'max_body_bytes'     => 65536,
        'rate_limit_per_min' => 240,    // per IP per tenant
        'enforce_origin'     => true,   // reject when Origin/Referer host
                                        // does not match the tenant domain
    ],

    // -----------------------------------------------------------------
    // Storage guardrails (§15.3). The shard alarm is a Phase 1
    // deliverable: a full shard means silently dropped events.
    // -----------------------------------------------------------------
    'storage' => [
        'shard_bytes_limit'     => 3221225472,  // 3 GiB
        'shard_warn_ratio'      => 0.80,        // alert at 2.4 GiB
        'processed_retain_days' => 30,          // replay window
    ],

    'alerts' => [
        'email_to'           => Env::get('ALERT_EMAIL_TO'),
        'email_from'         => Env::get('ALERT_EMAIL_FROM', 'odysseus@digifyce.com'),
        'renotify_after_min' => 360,
    ],

    // -----------------------------------------------------------------
    // Shopify
    // -----------------------------------------------------------------
    'shopify' => [
        'api_version' => Env::get('SHOPIFY_API_VERSION', '2025-07'),

        // Eight scopes, not the 75 in shopify_key_fetch/shopify_token_exchange.py.
        // read_all_orders and read_customers must ALSO be requested in the
        // Partner Dashboard app config — the scope string alone is not enough.
        // Without read_all_orders the API returns only 60 days of orders and
        // every retention metric is empty.
        'scopes' => 'read_all_orders,read_orders,read_customers,read_products,'
                  . 'read_checkouts,read_inventory,read_price_rules,read_locales',
    ],

    // Everything is stored UTC. Display timezone is per-tenant.
    'app' => [
        'timezone' => 'UTC',
        'debug'    => Env::bool('APP_DEBUG', false),
    ],
];
