<?php
/**
 * Project Odysseus — application configuration.
 *
 * This file IS tracked in git. It contains no credentials: everything
 * secret is read from .env at the repo root (see .env.example).
 *
 * Structural settings — paths, ingest limits, storage guardrails, Shopify
 * scopes — belong here so they are version-controlled and reviewable. The
 * server admin never edits this file; they only fill in .env.
 */

declare(strict_types=1);

require_once __DIR__ . '/../app/lib/Env.php';

Env::load(dirname(__DIR__) . '/.env');

$root = dirname(__DIR__);

return [

    // -----------------------------------------------------------------
    // Database — credentials from .env
    // -----------------------------------------------------------------
    'db' => [
        'host'          => Env::get('DB_HOST', 'localhost'),
        'port'          => Env::int('DB_PORT', 3306),
        'user'          => Env::require('DB_USER'),
        'pass'          => Env::get('DB_PASS', ''),

        // Hostinger prepends the account id to every database name.
        'prefix'        => Env::get('DB_PREFIX', ''),

        'core'          => Env::get('DB_CORE', 'odys_core'),
        'shard_pattern' => Env::get('DB_SHARD_PATTERN', 'odys_ev_{year}'),

        'charset'       => 'utf8mb4',
    ],

    // -----------------------------------------------------------------
    // Filesystem — all outside the document root.
    // storage/ and secrets/ are NOT in git; create them on the server.
    // -----------------------------------------------------------------
    'paths' => [
        'spool'     => $root . '/storage/spool',
        'processed' => $root . '/storage/processed',
        'failed'    => $root . '/storage/failed',
        'locks'     => $root . '/storage/locks',
        'logs'      => $root . '/storage/logs',
        'secrets'   => $root . '/secrets',
        'geolite'   => $root . '/secrets/GeoLite2-City.mmdb',
    ],

    'secrets' => [
        // Generated by bin/keygen.php, never written by hand.
        // Losing it makes every stored Shopify token unrecoverable.
        'master_key_file' => $root . '/secrets/master.key',
        'salt_dir'        => $root . '/secrets/salts',
    ],

    // -----------------------------------------------------------------
    // Single host, path-separated (§4.1). The collector path is short
    // because it is repeated in every beacon on every store.
    // -----------------------------------------------------------------
    'hosts' => [
        'base'           => Env::get('APP_BASE_URL', 'https://retention.digifyce.com'),
        'collect'        => rtrim(Env::get('APP_BASE_URL', 'https://retention.digifyce.com'), '/') . '/c.php',
        'oauth_redirect' => Env::get(
            'SHOPIFY_REDIRECT_URI',
            'https://retention.digifyce.com/oauth/callback.php'
        ),
    ],

    // -----------------------------------------------------------------
    // Ingest limits (§7.1). The write_key in the pixel snippet is PUBLIC
    // and is not a credential — these are the actual protections.
    // -----------------------------------------------------------------
    'ingest' => [
        'max_body_bytes'     => 65536,
        'rate_limit_per_min' => 240,    // per IP per tenant
        'enforce_origin'     => true,   // reject when Origin/Referer host
                                        // does not match the tenant domain
    ],

    // -----------------------------------------------------------------
    // Storage guardrails (§15.3). The shard alarm is a Phase 1
    // deliverable: a full shard means silently dropped events.
    // -----------------------------------------------------------------
    'storage' => [
        'shard_bytes_limit'     => 3221225472,  // 3 GiB
        'shard_warn_ratio'      => 0.80,        // alert at 2.4 GiB
        'processed_retain_days' => 30,          // replay window
    ],

    'alerts' => [
        'email_to'           => Env::get('ALERT_EMAIL_TO'),
        'email_from'         => Env::get('ALERT_EMAIL_FROM', 'odysseus@digifyce.com'),
        'renotify_after_min' => 360,
    ],

    // -----------------------------------------------------------------
    // Shopify
    // -----------------------------------------------------------------
    'shopify' => [
        'api_version' => Env::get('SHOPIFY_API_VERSION', '2025-07'),

        // Eight scopes, not the 75 in shopify_key_fetch/shopify_token_exchange.py.
        // read_all_orders and read_customers must ALSO be requested in the
        // Partner Dashboard app config — the scope string alone is not enough.
        // Without read_all_orders the API returns only 60 days of orders and
        // every retention metric is empty.
        'scopes' => 'read_all_orders,read_orders,read_customers,read_products,'
                  . 'read_checkouts,read_inventory,read_price_rules,read_locales',
    ],

    // Everything is stored UTC. Display timezone is per-tenant.
    'app' => [
        'timezone' => 'UTC',
        'debug'    => Env::bool('APP_DEBUG', false),
    ],
];
